const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Arr,
		C3.Behaviors.Flash,
		C3.Behaviors.Physics,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Exps.Text,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Cnds.Else
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{rakamlar: 0},
	{tiklanma: 0},
	{baliklar: 0},
	{balikci: 0},
	{anasayfa: 0},
	{Array: 0},
	{Flash: 0},
	{dogru: 0},
	{yanlis: 0},
	{yenile: 0},
	{kontrolet: 0},
	{ekran: 0},
	{Physics: 0},
	{balik: 0},
	{Problem: 0},
	{Touch: 0},
	{sepet: 0},
	{odemeT: 0},
	{sil: 0},
	{Browser: 0},
	{Sprite2: 0},
	{Sine: 0},
	{oynaButonu: 0},
	{oyunnasilButonu: 0},
	{SpriteFont: 0},
	{Sprite3: 0},
	{anasayfaButonu: 0},
	{Audio: 0},
	{Mouse: 0},
	{hover: 0},
	{grup: 0},
	{gruplar: 0},
	{balikadedi2: 0},
	{frameno: 0},
	{isim: 0},
	{isimler: 0},
	{balikadedi: 0},
	{balikfiyati: 0},
	{paraustu: 0},
	{odeme: 0},
	{cebindekipara: 0},
	{balikfiyati2: 0},
	{balikfiyati3: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	rakamlar: class extends self.ISpriteInstance {},
	baliklar: class extends self.ISpriteInstance {},
	balikci: class extends self.ISpriteInstance {},
	anasayfa: class extends self.ISpriteInstance {},
	Array: class extends self.IArrayInstance {},
	dogru: class extends self.ISpriteInstance {},
	yanlis: class extends self.ISpriteInstance {},
	yenile: class extends self.ISpriteInstance {},
	kontrolet: class extends self.ISpriteInstance {},
	ekran: class extends self.ISpriteInstance {},
	balik: class extends self.ISpriteInstance {},
	Problem: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	sepet: class extends self.ISpriteInstance {},
	odemeT: class extends self.ITextInstance {},
	sil: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	oynaButonu: class extends self.ISpriteInstance {},
	oyunnasilButonu: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	anasayfaButonu: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	hover: class extends self.ISpriteInstance {}
}